### ISSUE TITLE
Micronaut Picocli Guide: broken link in header

### ISSUE THREAD

**Issue by deining** [micronaut-projects/micronaut-picocli#112]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

- Visit latest version of [guide](https://micronaut-projects.github.io/micronaut-picocli/latest/guide/)
- Link `Configuration reference` in the header is broken.

![MicronautDocuBrokenLink](https://user-images.githubusercontent.com/18169566/99936959-b87b4d00-2d64-11eb-8f7c-3b6e0d7cd8c5.png)

### Expected Behaviour

Should link to latest version of Micronaut `Configuration reference`
https://docs.micronaut.io/latest/guide/configurationreference.html

**Another topic:** I realized that code samples in the Micronaut docu are given for Java, Kotlin and Groovy (which is good IMHO). This is not the case for the current micronaut - picocli guide. Having a first quick look at the .adoc sources, it looks like some postprocessing takes place for the multi language code sample. If you can guide me to the right track here, I'm willing to work on a pull request that provides Kotlin and Groovy version for the code samples in the micronaut picocli docu.

**Comment by sdelamo** [comment]
> Another topic: I realized that code samples in the Micronaut docu are given for Java, Kotlin and Groovy (which is good IMHO). This is not the case for the current micronaut - picocli guide. Having a first quick look at the .adoc sources, it looks like some postprocessing takes place for the multi language code sample. If you can guide me to the right track here, I'm willing to work on a pull request that provides Kotlin and Groovy version for the code samples in the micronaut picocli docu

@wetted can you create a PR which moves the hardcoded code samples from the asciidoc files to `test-suite`, `test-suite-kotlin` and `test-suite-groovy` so that a multi line snippet is shown. 


@deining the lack of configuration reference from this module is expected. Picocli does not have any configuration.

**Comment by timyates** [comment]
There's no @ConfigurationProperties, so no Configuration Reference.  This is as expected (though does look a bit odd)

As of Micronaut 4, it's not a 404 error, it's a page with no configuration on it (as there isn't any)

Closing this for now, as it's _now_ as expected
