### ISSUE TITLE
Guide to build a jar not working for  mvn

### ISSUE THREAD

**Issue by baztian** [micronaut-projects/micronaut-picocli#178]
### Steps to Reproduce

1. Create a cli app from the launcher
2. Follow the mvn instrcutions https://micronaut-projects.github.io/micronaut-picocli/3.0.0/guide/index.html
3. Go to "Running the Application"
4. Figure out how to "build" and then find out where to find the *.jar

### Expected Behaviour

I'd like to have some instructions in the template / in the guide on how to build the all.jar with mvn.

### Actual Behaviour

I need to run `./mvnw verify` in order to create a demo.jar which will end up in `target/demo.jar`.

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.5.9
- **JDK Version:** 11

**Comment by sdelamo** [comment]
You can [package your CLI with maven with `./mvwn package`](https://micronaut-projects.github.io/micronaut-maven-plugin/latest/examples/package.html)


@wetted maybe we could replace in the docs: 

> Now you can build the project and start the application. The build will create a ${project-name}-all.jar with all dependencies in build/libs. 

Something like: 

```
https://guides.micronaut.io/latest/executable-jar.html[Generate an executable Jar]. When you run this JAR, it executes the `MyCliAppCommand` command.

With Gradle: 


$ ./gradlew shadowJar
$ java -jar build/libs/my-cli-app-0.1-all.jar -v


With Maven Package: 

./mvnw package
$ java -jar target/my-cli-app-0.1.jar -v

````
