### ISSUE TITLE
Deprecate or remove PicocliTypeElementVisitor

### ISSUE THREAD

**Issue by remkop** [micronaut-projects/micronaut-picocli#29]
As per discussion in [this ticket](https://github.com/micronaut-projects/micronaut-picocli/issues/23#issuecomment-619529092), we want to emphasise to applications that create native-image applications with Micronaut and picocli that they should use the (picocli provided) `picocli-codegen` dependency to deal with reflection instead of the (Micronaut provided) combination of `micronaut-picocli` and `micronaut-graal`.

The [PicocliTypeElementVisitor](https://github.com/micronaut-projects/micronaut-picocli/blob/master/picocli/src/main/java/io/micronaut/configuration/picocli/annotation/PicocliTypeElementVisitor.java) should be deprecated (or even removed altogether?) in Micronaut 2.0 to signal to applications that they should use `picocli-codegen` instead.

**Comment by sdelamo** [comment]
I've deprecated PicocliTypeElementVistor. 

@remkop Could you review the output of a CLI application + `graalvm` feature in `micronaut-starter` and confirm it is correct?

**Comment by sdelamo** [comment]
@remkop  

From what I understood is that you think should generate: 

```groovy
dependencies {
    annotationProcessor("info.picocli:picocli-codegen:4.2.0")
    implementation("info.picocli:picocli")
    implementation("io.micronaut.picocli:micronaut-picocli")
...
}
```

Instead: 

```groovy
dependencies {
    annotationProcessor("io.micronaut:micronaut-graal")
    annotationProcessor("info.picocli:picocli-codegen:4.2.0")
    compileOnly("org.graalvm.nativeimage:svm")
    implementation("info.picocli:picocli")
    implementation("io.micronaut.picocli:micronaut-picocli")
...
}
```

this, we should not include 


```
    annotationProcessor("io.micronaut:micronaut-graal")
    compileOnly("org.graalvm.nativeimage:svm")
```

for cli apps with graalvm. 

Is that correct?

**Comment by ilopmar** [comment]
If Picocli already handles with all the GraalVM configuration I think we should remove our TypeElementVisitor. Even if it's there it will be executed and it's not what we want. 
We should document it as a possible breaking change in the unlikely case that some users are extending from it.

**Comment by sdelamo** [comment]
do you think that we should remove it instead of deprecating it and removing it later?

**Comment by ilopmar** [comment]
If it's not going to be used anymore, we can use the major version upgrade to directly remove it.

**Comment by remkop** [comment]
> @remkop
> 
> From what I understood is that you think should generate:
> 
> ```groovy
> dependencies {
>     annotationProcessor("info.picocli:picocli-codegen:4.2.0")
>     implementation("info.picocli:picocli")
>     implementation("io.micronaut.picocli:micronaut-picocli")
> ...
> }
> ```
> 
> Instead:
> 
> ```groovy
> dependencies {
>     annotationProcessor("io.micronaut:micronaut-graal")
>     annotationProcessor("info.picocli:picocli-codegen:4.2.0")
>     compileOnly("org.graalvm.nativeimage:svm")
>     implementation("info.picocli:picocli")
>     implementation("io.micronaut.picocli:micronaut-picocli")
> ...
> }
> ```
> 
> this, we should not include
> 
> ```
>     annotationProcessor("io.micronaut:micronaut-graal")
>     compileOnly("org.graalvm.nativeimage:svm")
> ```
> 
> for cli apps with graalvm.
> 
> Is that correct?

I am not 100% sure about the dependencies.

I agree with @ilopmar about removing rather than deprecating `PicocliTypeElementVisitor`: the `picocli-codegen` annotation processor will ensure that all program elements that are reflectively accessed _by picocli_ will be listed in the generated `reflect-config.json` file.  My understanding is that  `PicocliTypeElementVisitor` has the exact same responsibility so I think it is not needed.

But about the dependencies, I am not sure...

Note that if _Micronaut itself_ needs to reflectively access any program elements, that will not be covered by the `picocli-codegen` annotation processor. My (admittedly vague) understanding is that Micronaut also uses reflection for private fields/methods that have certain annotations. If that is the case, is it okay to remove `annotationProcessor("io.micronaut:micronaut-graal")` and `compileOnly("org.graalvm.nativeimage:svm")`? Do these dependencies not include other components than  `PicocliTypeElementVisitor`, that are needed by Micronaut itself to create correct/complete native images?

**Comment by sdelamo** [comment]
I've changed the PR to delete `PicocliTypeElementVisitor`
